logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG


server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/shopping-list1}
    driver-class-name: org.postgresql.Driver


