logging:
  level:
    root: INFO

server:
  port: 8090
  servlet:
    context-path: /shopping-list

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/shopping-list
    driver-class-name: org.postgresql.Driver

#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    username: sa
#    password:
#    url: jdbc:h2:mem:shopping-list
#    driver-class-name:  org.h2.Driver

