create table users
(
    id        int8 generated by default as identity,
    password  varchar(255) not null,
    user_name varchar(255) not null,
    primary key (id)
);


alter table if exists users
    add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);