create table shopping_items
(
    id      int8 generated by default as identity,
    name    varchar(255) not null,
    user_id int8,
    primary key (id)
);

alter table if exists shopping_items
    add constraint FKtpkopyby8qwu1noj4n4t3yuig
        foreign key (user_id)
            references users;